twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: /move_base/cmd_vel_nav
        timeout: 0.5
        priority: 10
      teleop:
        topic: /cmd_vel
        timeout: 0.5
        priority: 100