FROM althack/ros2:jazzy-gazebo

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
   && apt-get -y install --no-install-recommends libxkbcommon-x11-0 libxcb-xinerama0 x11-apps \
   # Clean up
   && apt-get autoremove -y \
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog

# RUN mkdir -p /var/run/user && chmod 755 /var/run/user
# RUN sudo chown ros:ros /var/run/user

# USER ros
# RUN rm -r /build /install /log
# Set up auto-source of workspace for ros user
#ARG WORKSPACE

RUN apt-get update \
   && apt-get -y install --no-install-recommends \
   ros-jazzy-navigation2 \
   ros-jazzy-nav2-bringup \
   ros-jazzy-twist-mux \
   ros-jazzy-robot-localization \
   ros-jazzy-slam-toolbox \
   ros-jazzy-foxglove-bridge \
   # Clean up
   && apt-get autoremove -y \
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog


WORKDIR /workspace
# COPY /src /src
COPY src src



# RUN git clone https://github.com/Slamtec/rplidar_sdk \
#       && cd rplidar_sdk \
#       && make

# RUN mkdir -p /var/run/user && chmod 755 /var/run/user
RUN sudo chown ros:ros /var/run/user

# Set up auto-source of workspace for ros user
ARG WORKSPACE
RUN echo "if [ -f ${WORKSPACE}/install/setup.bash ]; then source ${WORKSPACE}/install/setup.bash; fi" >> /home/ros/.bashrc

RUN rosdep update \
    && rosdep install --from-paths src --rosdistro jazzy -y \
ENV GZ_VERSION=harmonic
RUN source /opt/ros/jazzy/setup.bash \
    && colcon build


# RUN ros2 launch glados_bringup gazebo.launch.py

# COPY ./entrypoint.sh ./entrypoint.sh
# ENTRYPOINT ["entrypoint.sh"]
CMD ["bash"]
